services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # optional if you want Jenkins to control Docker too
    # environment:
      # - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    networks:
      - jenkins

  fake-vps:
    build:
      context: ./playground
      dockerfile: Dockerfile
    container_name: fake-vps
    ports:
      - "2222:22"
    restart: unless-stopped

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
  # jenkins-docker-certs:
  # openssh-server-config: